# Generated by Django 3.2.3 on 2021-06-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_sending',
            old_name='mail',
            new_name='Mail',
        ),
    ]
